### ISSUE TITLE
undefined is not an object (evaluating 'output.split')

### ISSUE THREAD

**Issue by kochsebastian** [believer/uebersicht-now-playing#1]
I get the following error.  
```
undefined is not an object (evaluating 'output.split')
export const render = ({ output, error }) => {
  const [
    state,
    artist,
    track,
    album,
    link,
    cover,
    position,
    duration,
  ] = output.split("::");
```

I just copied it into my widgets folder. Then this crror message appeared on my home screen.   
I'm running macOS Big Sur. A quick fix would be nice

**Comment by believer** [comment]
What track were you playing? Might be something in it that's not parsed correctly

**Comment by kochsebastian** [comment]
I was playing nothing. Spotify was open though

**Comment by believer** [comment]
I downloaded the zip and found the error. Unzipping creates a directory with the name `/now-playing.widget` when it needs to be `/now-playing`. If you rename the folder it should work!

I'll make a fix for it in the build. Thanks for finding the bug 😄
