### ISSUE TITLE
macOS Big Sur

### ISSUE THREAD

**Issue by GrimlocK38** [believer/uebersicht-now-playing#2]
Hi,

I just configured it but it does not appear. 

Thanks for help

**Comment by believer** [comment]
Hi, I'm using Big Sur as well. Do you have any errors in the debug console? Using Spotify, Itunes, or Sonos?

**Comment by GrimlocK38** [comment]
Hi,

1. log
<img width="1112" alt="log" src="https://user-images.githubusercontent.com/19632490/102708256-ef7c4a00-42a1-11eb-9ef4-4b1e064a0aea.png">



2. I use Musique
<img width="680" alt="musique" src="https://user-images.githubusercontent.com/19632490/102708140-00788b80-42a1-11eb-9d9f-82811ff95c03.png">

3. The widget is well listed
<img width="263" alt="nowplaying" src="https://user-images.githubusercontent.com/19632490/102708199-7f6dc400-42a1-11eb-927d-206973ca936d.png">

Thanks

**Comment by believer** [comment]
Oh, I wonder if it's because the app is named something else in French! I'll look into it, thanks for the logs and information!

**Comment by believer** [comment]
On closer inspection that doesn't seem to be it, I'm using Swedish macOS and the app is named "Musik" and that works. I reworked both the Spotify/Music part of the script as well as the Sonos part. Can you try `v1.3.6` and tell me if that works better?

**Comment by GrimlocK38** [comment]
Hi,

i will test this :)

**Comment by GrimlocK38** [comment]
we will get there. i just updated and still nothing.

here is log
<img width="1792" alt="ITRecords 1" src="https://user-images.githubusercontent.com/19632490/102869540-0f477580-443c-11eb-80c9-e655e7b71d9c.png">

**Comment by believer** [comment]
good good, at least something different! Let me see

**Comment by GrimlocK38** [comment]
For information. it's good ?.

<img width="181" alt="ITRecords 1" src="https://user-images.githubusercontent.com/19632490/102870053-c643f100-443c-11eb-856b-ceaa8858da63.png">

**Comment by believer** [comment]
There's a `now-playing.widget.zip` that you can use which has less content, but that should also work. I downloaded the zip and it worked for me.

It looks like you can expand the error in the console, does it provide any more information?

**Comment by GrimlocK38** [comment]
Hummm. In the console more errors but nothing is displayed. weird.

**Comment by believer** [comment]
Yeah, I don't have much to go on, sorry 😞

**Comment by GrimlocK38** [comment]
Hi,

I understand. already I have no more errors but we do not know where it is blocking. you tested on macOS big sur ?

My config
<img width="698" alt="ITRecords 1" src="https://user-images.githubusercontent.com/19632490/103170846-c9c5e680-4847-11eb-8107-5c113b4914c2.png">

**Comment by believer** [comment]
Yup, I'm running Big Sur myself. The application is called "Musik" (in Swedish) and not "Music" like I'm using in the code and that works, so I don't think so.

**Comment by GrimlocK38** [comment]
@believer Ok.I'm not lucky :)

**Comment by GrimlocK38** [comment]
<img width="1680" alt="ITRecords 1" src="https://user-images.githubusercontent.com/19632490/103179725-1da7ee00-488f-11eb-9076-6d4f8968dd89.png">

here is the error. it appears when the music is started

**Comment by believer** [comment]
`tell application "System Events"` would run even without any music playing. If the errors start only after you press play it would be somewhere in this section that the error occurs

```applescript
	if application "Music" is running then
		tell application "Music"
			if player state is playing then
				set link to ""
				set cover to ""
				set playerState to "playing"
				set trackName to name of current track
				set trackArtist to artist of current track
				set albumName to album of current track
				set trackDuration to duration of current track
				set playerPosition to player position
				set cover to my itunesArtwork()
				
				return playerState & "::" & trackArtist & "::" & trackName & "::" & albumName & "::" & link & "::" & cover & "::" & playerPosition & "::" & trackDuration
			end if
		end tell
	end if
```

Does it work if you remove the row for album artwork?

```applescript
set cover to my itunesArtwork()
```

Might be something in that function that's not working on your system? It's creating a temporary file with the artwork and base64 encoding it, then removes the temporary file.

**Comment by GrimlocK38** [comment]
@believer Thanks for the return. after deleting this line. still no display. by cons when I opened the script here is what it tells me

syntax error. "then" is expected but identifier found. maybe a new track. 

Thanks

<img width="812" alt="ITRecords 1" src="https://user-images.githubusercontent.com/19632490/103236993-a7ff5900-4946-11eb-86ac-3471dcb87195.png">

**Comment by believer** [comment]
That's the same error that's displayed in the console at least. I'm not sure why it's throwing a syntax error, it validates on my end. Maybe you can try removing functions and Spotify-related stuff until it validates to pinpoint the error? 😄

**Comment by GrimlocK38** [comment]
@believer I will test :)

**Comment by GrimlocK38** [comment]
> @believer I will test :)

**Comment by believer** [comment]
Ahh awesome, so the Spotify part of the code works with the Music app? The output looks correct :D Could you post the updated code so I can see what you changed?

**Comment by GrimlocK38** [comment]
@believer it's nice to see that it works :). back home I send you the file 😉

**Comment by GrimlocK38** [comment]
@believer Hey, here is the correction :)

[script.scpt.zip](https://github.com/believer/uebersicht-now-playing/files/5751186/script.scpt.zip)

**Comment by believer** [comment]
That made me find the real error, I'm guessing that you don't have Spotify installed and that's why it breaks! I uninstalled Spotify and got the same error as you. I'll fix that.

**Comment by GrimlocK38** [comment]
@believer Hi,

we did well to keep looking 😀 
Keep me informed. Great Work man. Thanks

**Comment by believer** [comment]
Can't find a good way of checking if the application is installed. The best way is to just remove the Spotify section from `script.scpt` if you don't have it installed 😅 

Anyway, thank you very much for all the debugging help!
